# Enable mouse control (clickable windows, panes, resizable panes, and text selection)
set -g mouse on

# Use vi-style keybindings in copy mode
setw -g mode-keys vi

# macOS system clipboard integration using pbcopy
# Copy selected text to the macOS clipboard when dragging with the mouse, without clearing the visual selection
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-no-clear "pbcopy"

# Allow using 'y' to copy text to the macOS clipboard while in copy mode
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"