#======================================================
#= TMUX PLUGIN MANAGER (TPM)
#======================================================
# For clean management of tmux plugins.

# List of plugins
# TPM is required to manage other plugins
set -g @plugin 'tmux-plugins/tpm'

# The plugin you want to install
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Enable full mouse controll support
set -g mouse on

# Initialize the plugin manager (must be at the very end of the file)
run '~/.tmux/plugins/tpm/tpm'